//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Site</summary>
	[PublishedContentModel("site")]
	public partial class Site : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "site";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Site(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Site, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Phone 1
		///</summary>
		[ImplementPropertyType("footerPhone1")]
		public string FooterPhone1
		{
			get { return this.GetPropertyValue<string>("footerPhone1"); }
		}

		///<summary>
		/// Footer Phone 2
		///</summary>
		[ImplementPropertyType("footerPhone2")]
		public string FooterPhone2
		{
			get { return this.GetPropertyValue<string>("footerPhone2"); }
		}

		///<summary>
		/// Images: Картинки с работами
		///</summary>
		[ImplementPropertyType("images")]
		public string Images
		{
			get { return this.GetPropertyValue<string>("images"); }
		}

		///<summary>
		/// Link for Insta
		///</summary>
		[ImplementPropertyType("linkForInsta")]
		public string LinkForInsta
		{
			get { return this.GetPropertyValue<string>("linkForInsta"); }
		}

		///<summary>
		/// Link for VK
		///</summary>
		[ImplementPropertyType("linkForVK")]
		public string LinkForVK
		{
			get { return this.GetPropertyValue<string>("linkForVK"); }
		}

		///<summary>
		/// Map Image
		///</summary>
		[ImplementPropertyType("mapImage")]
		public string MapImage
		{
			get { return this.GetPropertyValue<string>("mapImage"); }
		}

		///<summary>
		/// Menu
		///</summary>
		[ImplementPropertyType("menu")]
		public Newtonsoft.Json.Linq.JArray Menu
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JArray>("menu"); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return this.GetPropertyValue<string>("metaDescription"); }
		}

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return this.GetPropertyValue<string>("metaKeywords"); }
		}

		///<summary>
		/// Open Graph Description
		///</summary>
		[ImplementPropertyType("openGraphDescription")]
		public string OpenGraphDescription
		{
			get { return this.GetPropertyValue<string>("openGraphDescription"); }
		}

		///<summary>
		/// Open Graph Image
		///</summary>
		[ImplementPropertyType("openGraphImage")]
		public string OpenGraphImage
		{
			get { return this.GetPropertyValue<string>("openGraphImage"); }
		}

		///<summary>
		/// Open Graph Title
		///</summary>
		[ImplementPropertyType("openGraphTitle")]
		public string OpenGraphTitle
		{
			get { return this.GetPropertyValue<string>("openGraphTitle"); }
		}

		///<summary>
		/// Page Scripts: {script}{/script}
		///</summary>
		[ImplementPropertyType("pageScripts")]
		public string PageScripts
		{
			get { return this.GetPropertyValue<string>("pageScripts"); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return this.GetPropertyValue<string>("pageTitle"); }
		}

		///<summary>
		/// SubTitle
		///</summary>
		[ImplementPropertyType("priceSubTitle")]
		public string PriceSubTitle
		{
			get { return this.GetPropertyValue<string>("priceSubTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("priceTitle")]
		public string PriceTitle
		{
			get { return this.GetPropertyValue<string>("priceTitle"); }
		}

		///<summary>
		/// Products
		///</summary>
		[ImplementPropertyType("products")]
		public Archetype.Models.ArchetypeModel Products
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("products"); }
		}

		///<summary>
		/// Services
		///</summary>
		[ImplementPropertyType("services")]
		public Archetype.Models.ArchetypeModel Services
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("services"); }
		}

		///<summary>
		/// SubTitle
		///</summary>
		[ImplementPropertyType("serviceSubTitle")]
		public string ServiceSubTitle
		{
			get { return this.GetPropertyValue<string>("serviceSubTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("serviceTitle")]
		public string ServiceTitle
		{
			get { return this.GetPropertyValue<string>("serviceTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}
}
